/**
 * Regenerate src/palettes/ucrc-boxtype.membership.ts from the served UCRC boxes parquet.
 *
 * The management app owns box-type grouping (BoxType.parent); it publishes `box_type_code` +
 * `box_type_group` on the `ucrc_boxes` related parquet. This reads the distinct (code -> group)
 * pairs and writes them out as a committed snapshot the palette consumes. Colours + shade order
 * stay in ucrc-boxtype.ts — this only refreshes membership.
 *
 * Usage: npm run gen:boxtype-membership   (run after the boxes export publishes the new columns)
 */
import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { asyncBufferFromUrl, parquetReadObjects } from 'hyparquet';
import { compressors } from 'hyparquet-compressors';

const GEOPARQUET_BASE = (process.env.GEOPARQUET_BASE
    ?? 'https://maps-assets.geology.utah.gov/warehouse').replace(/\/+$/, '');
// The boxes related parquet lives under the wells serving topic.
const URL = `${GEOPARQUET_BASE}/geoparquet/enmin_ucrc_wells/related/enmin_ucrc_boxes.parquet`;
const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'palettes', 'ucrc-boxtype.membership.ts');

async function main(): Promise<void> {
    const file = await asyncBufferFromUrl({ url: URL });
    const rows = await parquetReadObjects({ file, columns: ['box_type_code', 'box_type_group'], compressors });
    const seen = new Map<string, string>();
    for (const r of rows) {
        const code = typeof r.box_type_code === 'string' ? r.box_type_code.trim() : '';
        const group = typeof r.box_type_group === 'string' ? r.box_type_group.trim() : '';
        if (code && !seen.has(code)) seen.set(code, group || 'OTHER');
    }
    const entries = [...seen]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([code, group]) => `    { code: ${JSON.stringify(code)}, group: ${JSON.stringify(group)} },`)
        .join('\n');
    const body = `// GENERATED by scripts/gen-boxtype-membership.ts — do not edit by hand.
//
// Box type code -> colour group, read from the served \`ucrc_boxes\` parquet. The UCRC management
// app owns this mapping (BoxType.parent tree); this file is a committed snapshot of it. Colours +
// shade order are NOT here — those live in ucrc-boxtype.ts (ugs-styles owns style).
export const UCRC_BOX_MEMBERSHIP: readonly { code: string; group: string }[] = [
${entries}
];
`;
    await writeFile(OUT, body);
    console.log(`[boxtype-membership] wrote ${seen.size} box types -> ${OUT}`);
}

try { await main(); } catch (err) { console.error(err); process.exit(1); }
