/**
 * Regenerate src/palettes/ucrc-boxtype.membership.ts from the served UCRC boxes parquet.
 *
 * The management app owns box-type grouping (BoxType.parent); it publishes `box_type_code` +
 * `box_type_group` on the `ucrc_boxes` related parquet. This reads the distinct (code -> group)
 * pairs and writes them out as a committed snapshot the palette consumes. Colors + shade order
 * stay in ucrc-boxtype.ts — this only refreshes membership.
 *
 * Usage: npm run gen:boxtype-membership   (run after the boxes export publishes the new columns)
 *        npm run gen:boxtype-membership -- --force   (write even if the sanity check fails)
 */
import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { asyncBufferFromUrl, parquetReadObjects } from 'hyparquet';
import { compressors } from 'hyparquet-compressors';
import { UCRC_BOX_GROUP_ORDER } from '../src/palettes/ucrc-boxtype';

const GEOPARQUET_BASE = (process.env.GEOPARQUET_BASE
    ?? 'https://maps-assets.geology.utah.gov/warehouse').replace(/\/+$/, '');
// The boxes related parquet lives under the wells serving topic.
const URL = `${GEOPARQUET_BASE}/geoparquet/enmin_ucrc_wells/related/enmin_ucrc_boxes.parquet`;
const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'palettes', 'ucrc-boxtype.membership.ts');

async function main(): Promise<void> {
    const file = await asyncBufferFromUrl({ url: URL });
    const rows = await parquetReadObjects({ file, columns: ['box_type_code', 'box_type_group'], compressors });
    const seen = new Map<string, string>();
    for (const r of rows) {
        const code = typeof r.box_type_code === 'string' ? r.box_type_code.trim() : '';
        const group = typeof r.box_type_group === 'string' ? r.box_type_group.trim() : '';
        if (code && !seen.has(code)) seen.set(code, group || 'OTHER');
    }
    // Sanity check the export before overwriting a good snapshot with a bad one.
    //
    // `box_type_group` is `BoxType.category.code` — `parent or self` — so a type whose parent is
    // wrong doesn't error, it just lands in the wrong bucket. In July 2026 every core type in the
    // live export was parented to Other, so a blind regen would have moved ~70k boxes' worth of
    // BUTTS/SLABS/WHOLE CORE/SPOT CORES/SKELETONIZED CORE/CORESAMPLES to grey and quietly removed
    // the purple from the map. A group we have a colour for going to ZERO members is not a
    // legitimate state — it means the app's BoxType tree lost a parent, not that the data changed.
    const present = new Set([...seen.values()].map((g) => g.toUpperCase()));
    const missing = UCRC_BOX_GROUP_ORDER.filter((g) => g !== 'OTHER' && !present.has(g));
    if (missing.length && !process.argv.includes('--force')) {
        console.error(
            `[boxtype-membership] REFUSING TO WRITE — no box type in the export belongs to: ${missing.join(', ')}.\n` +
            `  Groups found: ${[...present].sort().join(', ') || '(none)'}\n` +
            '  This is an upstream data problem: the UCRC app publishes box_type_group from\n' +
            '  BoxType.category (parent or self), so an unparented/mis-parented type falls into OTHER.\n' +
            '  Fix the BoxType parents in the management app, re-run its publish, then regenerate.\n' +
            '  Re-run with --force only if a group genuinely has no members any more.',
        );
        process.exit(1);
    }

    const entries = [...seen]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([code, group]) => `    { code: ${JSON.stringify(code)}, group: ${JSON.stringify(group)} },`)
        .join('\n');
    const body = `// GENERATED by scripts/gen-boxtype-membership.ts — do not edit by hand.
//
// Box type code -> color group, read from the served \`ucrc_boxes\` parquet. The UCRC management
// app owns this mapping (BoxType.parent tree); this file is a committed snapshot of it. Colors +
// shade order are NOT here — those live in ucrc-boxtype.ts (ugs-styles owns style).
export const UCRC_BOX_MEMBERSHIP: readonly { code: string; group: string }[] = [
${entries}
];
`;
    await writeFile(OUT, body);
    console.log(`[boxtype-membership] wrote ${seen.size} box types -> ${OUT}`);
}

try { await main(); } catch (err) { console.error(err); process.exit(1); }
